Module 1 Project Exercise
pm141088/DevOps-Course-Starter pull request #1
Opened 2020-06-05 09:16 UTC by pm141088

2020-06-10 15:07 UTC, Jonesey13 commented on app.py
> +from flask_modus import Modus
You probably don't want to import this as it doesn't actually change the nature of requests being made to the flask server (e.g. POSTs override to DELETEs will still actually get send as POSTs)

Also this library: 

1. Needs to be added to requirements.txt to work (this needs to run in a virtual environment; see the README file)
1. Relies on an obsolete of werkzeug

2020-06-10 15:09 UTC, Jonesey13 commented on app.py
> +
Don't really need all these line breaks

2020-06-10 15:11 UTC, Jonesey13 commented on app.py
> +        new_item = req['title']
Probably want to validate against the case where title is empty (i.e. add server side validation along the client side validation you have below)

2020-06-10 15:14 UTC, Jonesey13 commented on app.py
> +        #found_item.status = request.form['status']
As we're using source control obsolete code like this can be safely removed

2020-06-10 15:14 UTC, Jonesey13 commented on app.py
> +# Edit an item
Redundant comment

2020-06-10 15:18 UTC, Jonesey13 commented on session_items.py
> +        save_item(item)
This line does nothing as the item has already been deleted

2020-06-10 15:20 UTC, Jonesey13 commented on templates/delete_item.html
> +        <tr>
This should be on a new level of indentation (to show its inside the `{% ... %}` block.

2020-06-10 15:23 UTC, Jonesey13 commented on app.py
> +        session.add_item(new_item)
This doesn't update the status

2020-06-10 15:24 UTC, Jonesey13 commented on templates/edit_item.html
> +    <form method="POST" action="{{url_for('read_item', id=found_item.id)}}?_method=PATCH">
This endpoint doesn't actually update the item

2020-06-10 15:25 UTC, Jonesey13 commented on templates/edit_item.html
> +      <input type="text" size="50" name="title" value="{{ found_item.title }}">
Needs a `required` attribute

2020-06-10 15:30 UTC, Jonesey13 requested changes
Nearly there! Currently the Flask-Modus dependency is preventing this PR from passing this Module (as the code doesn't work in the virtual environment).

Apart from that the core exercise goals work without issue.

I've also left some comments regarding the stretch goals (in particular the statuses don't appear to work).

2020-06-10 17:09 UTC, pat-morris commented on app.py
> +from flask_modus import Modus
Thanks, Alex. As it's obsolete, I have uninstalled the flask-modus package and removed references to it in my app.py file. I'll have a look for an alternative.

2020-06-11 00:34 UTC, pm141088 commented on app.py
> +
Agreed! Line breaks have now been removed! Perhaps I should also do this when writing emails ;)

2020-06-11 00:36 UTC, pm141088 commented on session_items.py
> +        save_item(item)
Doh! That is a good point, at the time it made perfect sense! :)

2020-06-11 00:40 UTC, pm141088 commented on app.py
> +        session.add_item(new_item)
I've reduced the scope here, initially I was trying to allow users the option of updatating two fields i.e. status and title... this proved difficult! I then realised the stretch goal was only asking to add functionality to mark an item as completed i.e. only one field needed to change! This made the process a lot easier to solve!

2020-06-11 00:42 UTC, pm141088 commented on templates/edit_item.html
> +    <form method="POST" action="{{url_for('read_item', id=found_item.id)}}?_method=PATCH">
Ah yes, sorry about that! I uninstall the flask-modus module and made some changes in the app.py and read_item.html. The edit_item.html file is now redundant!

2020-06-25 21:16 UTC, merged